### ISSUE TITLE
Error using bot.listSessions (line 39) Invalid argument at position 1. 'ophys' is invalid

### ISSUE THREAD

**Issue by yanndebray** [MATLAB-Community-Toolboxes-at-INCF/Brain-Observatory-Toolbox#178]
Replication steps: 
- Open [Version 0.9.4.1](https://www.mathworks.com/matlabcentral/fileexchange/90900-brain-observatory-toolbox#version_history_tab) in MATLAB Online: https://matlab.mathworks.com/open/fileexchange/v1?id=90900
- `bot.README`
- Run the script (F5)

Following line errors:
```matlab
availSessions = bot.listSessions('ophys')
```

**Error:**
```
Error using bot.listSessions (line 39)
Invalid argument at position 1. 'ophys' is invalid. Value must be 'VisualCoding' or 'VisualBehavior'.
```

**Comment by stevevanhooser** [comment]
Thanks @yanndebray , should be fixed now

**Comment by stevevanhooser** [comment]
Thanks @ehennestad for quick fix!
