### ISSUE TITLE
Add gettingStarted.mlx to top-level directory

### ISSUE THREAD

**Issue by stevevanhooser** [MATLAB-Community-Toolboxes-at-INCF/Brain-Observatory-Toolbox#183]
Should basically have the readme contents in it

( I think Vijay was going to take this one? )

**Comment by vijayiyer05** [comment]
I've created a GettingStarted live script that, to first order, clones the first sections of the README. 

It contains several updates. Some of which represent suggested mirrored README updates (e.g., breaking up into two tables, so neither is too wide). Some of which are changes specific to the live script, e.g., using a single column w/ OPEN links for the examples vs two columns for viewing/running on File Exchange & MATLAB Online.  

@stevevanhooser and/or @ehennestad : can you take a look over and comment if this seems high-level on the right track? And any additional suggestions welcomed.  

If it's close to right track, I can turn it into a pull request.

**Comment by stevevanhooser** [comment]
I like it, makes sense to me

**Comment by stevevanhooser** [comment]
(Also, if anyone opens, the file is not a zip, it is a mlx)
